name: bomb

on:
  push:
    branches:
      - main
  schedule:
    - cron: "0 0 * * *"

jobs:
  autogreen:
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v2
      - name: Auto bomb
        run: |
          git config --local user.email "341796767@qq.com"
          git config --local user.name "PY-GZKY"
          git remote set-url origin https://${{ github.actor }}:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}
          git pull --rebase
          git commit --allow-empty -m booooooooob !!!!
          git push